name: Upload Website

on:
  push:
    branches:
    - "main"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::928120649998:role/github-actions-cloud-resume
        aws-region: us-east-1

    - name: Sync to S3
      run: aws s3 sync . s3://www.jameswurbel.com --acl public-read --delete --exclude '.git/*' --exclude '.github/*' --exclude 'README.md' --exclude 'docs/*'

    - name: Invalidate CloudFront
      run: aws cloudfront create-invalidation --distribution-id E1PXVB1P5WATCS --paths "/*"
